In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../train.csv")

print("Dataset Loaded")

Dataset Loaded

In [2]:
# House Age Feature

df['HouseAge'] = (
    df['YrSold'] - df['YearBuilt']
)

df[['HouseAge']].head()

   HouseAge
0         5
1        31
2         7
3        91
4         8

In [3]:
# Total Square Feet

df['TotalSF'] = (
    df['TotalBsmtSF']
    + df['1stFlrSF']
    + df['2ndFlrSF']
)

df[['TotalSF']].head()

   TotalSF
0     2566
1     2524
2     2706
3     2473
4     3343

In [4]:
# Total Bathrooms

df['TotalBath'] = (
    df['FullBath']
    + (0.5 * df['HalfBath'])
    + df['BsmtFullBath']
    + (0.5 * df['BsmtHalfBath'])
)

df[['TotalBath']].head()

   TotalBath
0        3.5
1        2.5
2        3.5
3        2.0
4        3.5

In [5]:
# Log Transformation

df['SalePrice'] = np.log1p(
    df['SalePrice']
)

df[['SalePrice']].head()

   SalePrice
0  12.247699
1  12.109016
2  12.317171
3  11.849405
4  12.429220